/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminProductsRouteRouteImport } from './routes/admin/products/route'
import { Route as AdminGalleryRouteRouteImport } from './routes/admin/gallery/route'
import { Route as PublicGalleryRouteRouteImport } from './routes/_public/gallery/route'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSessionsIndexRouteImport } from './routes/admin/sessions/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminGalleryIndexRouteImport } from './routes/admin/gallery/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as PublicGalleryIndexRouteImport } from './routes/_public/gallery/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminSettingsSecurityRouteImport } from './routes/admin/settings/security'
import { Route as AdminSettingsProfileRouteImport } from './routes/admin/settings/profile'
import { Route as PublicGallerySlugRouteImport } from './routes/_public/gallery/$slug'
import { Route as AdminGallerySectionsRouteRouteImport } from './routes/admin/gallery/sections/route'
import { Route as AdminProductsProductIdIndexRouteImport } from './routes/admin/products/$productId/index'
import { Route as AdminGallerySectionsIndexRouteImport } from './routes/admin/gallery/sections/index'
import { Route as AdminGallerySectionsSectionIdIndexRouteImport } from './routes/admin/gallery/sections/$sectionId/index'
import { Route as ApiAdminProductsVariantsVariantIdImagesRouteImport } from './routes/api/admin/products/variants/$variantId/images'
import { Route as ApiAdminGallerySectionsSectionIdImagesRouteImport } from './routes/api/admin/gallery/sections/$sectionId/images'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRouteRoute = AdminProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryRouteRoute = AdminGalleryRouteRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicGalleryRouteRoute = PublicGalleryRouteRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSessionsIndexRoute = AdminSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRouteRoute,
} as any)
const AdminGalleryIndexRoute = AdminGalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGalleryRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicGalleryIndexRoute = PublicGalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicGalleryRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsSecurityRoute = AdminSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsProfileRoute = AdminSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const PublicGallerySlugRoute = PublicGallerySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicGalleryRouteRoute,
} as any)
const AdminGallerySectionsRouteRoute =
  AdminGallerySectionsRouteRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => AdminGalleryRouteRoute,
  } as any)
const AdminProductsProductIdIndexRoute =
  AdminProductsProductIdIndexRouteImport.update({
    id: '/$productId/',
    path: '/$productId/',
    getParentRoute: () => AdminProductsRouteRoute,
  } as any)
const AdminGallerySectionsIndexRoute =
  AdminGallerySectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminGallerySectionsRouteRoute,
  } as any)
const AdminGallerySectionsSectionIdIndexRoute =
  AdminGallerySectionsSectionIdIndexRouteImport.update({
    id: '/$sectionId/',
    path: '/$sectionId/',
    getParentRoute: () => AdminGallerySectionsRouteRoute,
  } as any)
const ApiAdminProductsVariantsVariantIdImagesRoute =
  ApiAdminProductsVariantsVariantIdImagesRouteImport.update({
    id: '/api/admin/products/variants/$variantId/images',
    path: '/api/admin/products/variants/$variantId/images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminGallerySectionsSectionIdImagesRoute =
  ApiAdminGallerySectionsSectionIdImagesRouteImport.update({
    id: '/api/admin/gallery/sections/$sectionId/images',
    path: '/api/admin/gallery/sections/$sectionId/images',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/gallery': typeof PublicGalleryRouteRouteWithChildren
  '/admin/gallery': typeof AdminGalleryRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/gallery/sections': typeof AdminGallerySectionsRouteRouteWithChildren
  '/gallery/$slug': typeof PublicGallerySlugRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/gallery/': typeof PublicGalleryIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/admin/gallery/sections/': typeof AdminGallerySectionsIndexRoute
  '/admin/products/$productId/': typeof AdminProductsProductIdIndexRoute
  '/admin/gallery/sections/$sectionId/': typeof AdminGallerySectionsSectionIdIndexRoute
  '/api/admin/gallery/sections/$sectionId/images': typeof ApiAdminGallerySectionsSectionIdImagesRoute
  '/api/admin/products/variants/$variantId/images': typeof ApiAdminProductsVariantsVariantIdImagesRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/gallery/$slug': typeof PublicGallerySlugRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/gallery': typeof PublicGalleryIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/gallery': typeof AdminGalleryIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/sessions': typeof AdminSessionsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/admin/gallery/sections': typeof AdminGallerySectionsIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdIndexRoute
  '/admin/gallery/sections/$sectionId': typeof AdminGallerySectionsSectionIdIndexRoute
  '/api/admin/gallery/sections/$sectionId/images': typeof ApiAdminGallerySectionsSectionIdImagesRoute
  '/api/admin/products/variants/$variantId/images': typeof ApiAdminProductsVariantsVariantIdImagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_public/gallery': typeof PublicGalleryRouteRouteWithChildren
  '/admin/gallery': typeof AdminGalleryRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/gallery/sections': typeof AdminGallerySectionsRouteRouteWithChildren
  '/_public/gallery/$slug': typeof PublicGallerySlugRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_public/gallery/': typeof PublicGalleryIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/admin/gallery/sections/': typeof AdminGallerySectionsIndexRoute
  '/admin/products/$productId/': typeof AdminProductsProductIdIndexRoute
  '/admin/gallery/sections/$sectionId/': typeof AdminGallerySectionsSectionIdIndexRoute
  '/api/admin/gallery/sections/$sectionId/images': typeof ApiAdminGallerySectionsSectionIdImagesRoute
  '/api/admin/products/variants/$variantId/images': typeof ApiAdminProductsVariantsVariantIdImagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/gallery'
    | '/admin/gallery'
    | '/admin/products'
    | '/admin/settings'
    | '/api/$'
    | '/admin/'
    | '/auth/'
    | '/admin/gallery/sections'
    | '/gallery/$slug'
    | '/admin/settings/profile'
    | '/admin/settings/security'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/gallery/'
    | '/admin/categories/'
    | '/admin/gallery/'
    | '/admin/products/'
    | '/admin/sessions/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/admin/gallery/sections/'
    | '/admin/products/$productId/'
    | '/admin/gallery/sections/$sectionId/'
    | '/api/admin/gallery/sections/$sectionId/images'
    | '/api/admin/products/variants/$variantId/images'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/$'
    | '/'
    | '/admin'
    | '/auth'
    | '/gallery/$slug'
    | '/admin/settings/profile'
    | '/admin/settings/security'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/gallery'
    | '/admin/categories'
    | '/admin/gallery'
    | '/admin/products'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/gallery/sections'
    | '/admin/products/$productId'
    | '/admin/gallery/sections/$sectionId'
    | '/api/admin/gallery/sections/$sectionId/images'
    | '/api/admin/products/variants/$variantId/images'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/auth'
    | '/_public/gallery'
    | '/admin/gallery'
    | '/admin/products'
    | '/admin/settings'
    | '/api/$'
    | '/_public/'
    | '/admin/'
    | '/auth/'
    | '/admin/gallery/sections'
    | '/_public/gallery/$slug'
    | '/admin/settings/profile'
    | '/admin/settings/security'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_public/gallery/'
    | '/admin/categories/'
    | '/admin/gallery/'
    | '/admin/products/'
    | '/admin/sessions/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/admin/gallery/sections/'
    | '/admin/products/$productId/'
    | '/admin/gallery/sections/$sectionId/'
    | '/api/admin/gallery/sections/$sectionId/images'
    | '/api/admin/products/variants/$variantId/images'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiAdminGallerySectionsSectionIdImagesRoute: typeof ApiAdminGallerySectionsSectionIdImagesRoute
  ApiAdminProductsVariantsVariantIdImagesRoute: typeof ApiAdminProductsVariantsVariantIdImagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/sessions/': {
      id: '/admin/sessions/'
      path: '/sessions'
      fullPath: '/admin/sessions/'
      preLoaderRoute: typeof AdminSessionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
    '/admin/gallery/': {
      id: '/admin/gallery/'
      path: '/'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AdminGalleryIndexRouteImport
      parentRoute: typeof AdminGalleryRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/gallery/': {
      id: '/_public/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof PublicGalleryIndexRouteImport
      parentRoute: typeof PublicGalleryRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/security': {
      id: '/admin/settings/security'
      path: '/security'
      fullPath: '/admin/settings/security'
      preLoaderRoute: typeof AdminSettingsSecurityRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/profile': {
      id: '/admin/settings/profile'
      path: '/profile'
      fullPath: '/admin/settings/profile'
      preLoaderRoute: typeof AdminSettingsProfileRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_public/gallery/$slug': {
      id: '/_public/gallery/$slug'
      path: '/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof PublicGallerySlugRouteImport
      parentRoute: typeof PublicGalleryRouteRoute
    }
    '/admin/gallery/sections': {
      id: '/admin/gallery/sections'
      path: '/sections'
      fullPath: '/admin/gallery/sections'
      preLoaderRoute: typeof AdminGallerySectionsRouteRouteImport
      parentRoute: typeof AdminGalleryRouteRoute
    }
    '/admin/products/$productId/': {
      id: '/admin/products/$productId/'
      path: '/$productId'
      fullPath: '/admin/products/$productId/'
      preLoaderRoute: typeof AdminProductsProductIdIndexRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
    '/admin/gallery/sections/': {
      id: '/admin/gallery/sections/'
      path: '/'
      fullPath: '/admin/gallery/sections/'
      preLoaderRoute: typeof AdminGallerySectionsIndexRouteImport
      parentRoute: typeof AdminGallerySectionsRouteRoute
    }
    '/admin/gallery/sections/$sectionId/': {
      id: '/admin/gallery/sections/$sectionId/'
      path: '/$sectionId'
      fullPath: '/admin/gallery/sections/$sectionId/'
      preLoaderRoute: typeof AdminGallerySectionsSectionIdIndexRouteImport
      parentRoute: typeof AdminGallerySectionsRouteRoute
    }
    '/api/admin/products/variants/$variantId/images': {
      id: '/api/admin/products/variants/$variantId/images'
      path: '/api/admin/products/variants/$variantId/images'
      fullPath: '/api/admin/products/variants/$variantId/images'
      preLoaderRoute: typeof ApiAdminProductsVariantsVariantIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/gallery/sections/$sectionId/images': {
      id: '/api/admin/gallery/sections/$sectionId/images'
      path: '/api/admin/gallery/sections/$sectionId/images'
      fullPath: '/api/admin/gallery/sections/$sectionId/images'
      preLoaderRoute: typeof ApiAdminGallerySectionsSectionIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicGalleryRouteRouteChildren {
  PublicGallerySlugRoute: typeof PublicGallerySlugRoute
  PublicGalleryIndexRoute: typeof PublicGalleryIndexRoute
}

const PublicGalleryRouteRouteChildren: PublicGalleryRouteRouteChildren = {
  PublicGallerySlugRoute: PublicGallerySlugRoute,
  PublicGalleryIndexRoute: PublicGalleryIndexRoute,
}

const PublicGalleryRouteRouteWithChildren =
  PublicGalleryRouteRoute._addFileChildren(PublicGalleryRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicGalleryRouteRoute: typeof PublicGalleryRouteRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicGalleryRouteRoute: PublicGalleryRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminGallerySectionsRouteRouteChildren {
  AdminGallerySectionsIndexRoute: typeof AdminGallerySectionsIndexRoute
  AdminGallerySectionsSectionIdIndexRoute: typeof AdminGallerySectionsSectionIdIndexRoute
}

const AdminGallerySectionsRouteRouteChildren: AdminGallerySectionsRouteRouteChildren =
  {
    AdminGallerySectionsIndexRoute: AdminGallerySectionsIndexRoute,
    AdminGallerySectionsSectionIdIndexRoute:
      AdminGallerySectionsSectionIdIndexRoute,
  }

const AdminGallerySectionsRouteRouteWithChildren =
  AdminGallerySectionsRouteRoute._addFileChildren(
    AdminGallerySectionsRouteRouteChildren,
  )

interface AdminGalleryRouteRouteChildren {
  AdminGallerySectionsRouteRoute: typeof AdminGallerySectionsRouteRouteWithChildren
  AdminGalleryIndexRoute: typeof AdminGalleryIndexRoute
}

const AdminGalleryRouteRouteChildren: AdminGalleryRouteRouteChildren = {
  AdminGallerySectionsRouteRoute: AdminGallerySectionsRouteRouteWithChildren,
  AdminGalleryIndexRoute: AdminGalleryIndexRoute,
}

const AdminGalleryRouteRouteWithChildren =
  AdminGalleryRouteRoute._addFileChildren(AdminGalleryRouteRouteChildren)

interface AdminProductsRouteRouteChildren {
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsProductIdIndexRoute: typeof AdminProductsProductIdIndexRoute
}

const AdminProductsRouteRouteChildren: AdminProductsRouteRouteChildren = {
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsProductIdIndexRoute: AdminProductsProductIdIndexRoute,
}

const AdminProductsRouteRouteWithChildren =
  AdminProductsRouteRoute._addFileChildren(AdminProductsRouteRouteChildren)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsProfileRoute: typeof AdminSettingsProfileRoute
  AdminSettingsSecurityRoute: typeof AdminSettingsSecurityRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsProfileRoute: AdminSettingsProfileRoute,
  AdminSettingsSecurityRoute: AdminSettingsSecurityRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminGalleryRouteRoute: typeof AdminGalleryRouteRouteWithChildren
  AdminProductsRouteRoute: typeof AdminProductsRouteRouteWithChildren
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminSessionsIndexRoute: typeof AdminSessionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminGalleryRouteRoute: AdminGalleryRouteRouteWithChildren,
  AdminProductsRouteRoute: AdminProductsRouteRouteWithChildren,
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminSessionsIndexRoute: AdminSessionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiAdminGallerySectionsSectionIdImagesRoute:
    ApiAdminGallerySectionsSectionIdImagesRoute,
  ApiAdminProductsVariantsVariantIdImagesRoute:
    ApiAdminProductsVariantsVariantIdImagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
